import { notFound } from "next/navigation";
import { hasLocale, type Locale } from "@/lib/i18n";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  return {
    title: locale === "zh" ? "服务条款" : "Terms of Service",
  };
}

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(locale)) notFound();
  const isZh = locale === "zh";

  return (
    <div className="flex flex-1 flex-col">
      <section className="mx-auto w-full max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight">
          {isZh ? "服务条款" : "Terms of Service"}
        </h1>
        <p className="mt-2 text-sm text-muted">
          {isZh ? "最后更新：2026年3月29日" : "Last updated: March 29, 2026"}
        </p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "1. 服务概述" : "1. Overview"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "JY Consultant Service（以下简称&ldquo;本平台&rdquo;）是一个AI驱动的商业咨询平台，提供行业洞察、市场分析、竞品分析和战略规划等服务。使用本平台即表示您同意以下条款。"
                : "JY Consultant Service (\"the Platform\") is an AI-powered business consulting platform providing industry insights, market analysis, competitor analysis, and strategy planning services. By using the Platform, you agree to these terms."}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "2. AI生成内容" : "2. AI-Generated Content"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "本平台提供的分析和建议由人工智能生成，仅供参考。我们不保证AI生成内容的准确性、完整性或适用性。用户在做出商业决策前应结合专业顾问意见进行独立判断。"
                : "Analysis and recommendations provided by the Platform are generated by artificial intelligence and are for informational purposes only. We do not guarantee the accuracy, completeness, or applicability of AI-generated content. Users should exercise independent judgment and consult professional advisors before making business decisions."}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "3. 使用限制" : "3. Acceptable Use"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "用户不得将本平台用于任何非法目的或违反适用法律法规的活动。禁止对平台进行逆向工程、滥用API或尝试未经授权的访问。"
                : "Users may not use the Platform for any illegal purpose or in violation of applicable laws. Reverse engineering, API abuse, or unauthorized access attempts are prohibited."}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "4. 知识产权" : "4. Intellectual Property"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "本平台的设计、代码、品牌和案例研究内容均受知识产权保护。用户可以将AI生成的咨询建议用于个人或商业用途，但不得转售或再分发平台本身的内容。"
                : "The Platform's design, code, branding, and case study content are protected by intellectual property rights. Users may use AI-generated consulting advice for personal or commercial purposes but may not resell or redistribute the Platform's content itself."}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "5. 免责声明" : "5. Disclaimer of Warranties"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "本平台按&ldquo;原样&rdquo;提供，不作任何明示或暗示的保证。我们不对因使用本平台而产生的任何直接、间接、附带或后果性损失承担责任。"
                : "The Platform is provided \"as is\" without warranties of any kind, either express or implied. We shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of the Platform."}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "6. 条款修改" : "6. Changes to Terms"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "我们保留随时修改本条款的权利。修改后的条款将在平台上发布后立即生效。继续使用本平台即表示您接受修改后的条款。"
                : "We reserve the right to modify these terms at any time. Updated terms will take effect immediately upon posting on the Platform. Continued use of the Platform constitutes acceptance of the modified terms."}
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">
              {isZh ? "7. 联系方式" : "7. Contact"}
            </h2>
            <p className="mt-2">
              {isZh
                ? "如有任何问题，请联系我们："
                : "If you have any questions, please contact us at:"}{" "}
              <a
                href="mailto:contact@jytech.us"
                className="text-accent-light underline"
              >
                contact@jytech.us
              </a>
            </p>
          </section>
        </div>
      </section>
    </div>
  );
}
